### ISSUE TITLE
Switch from Homu to Bors

### ISSUE THREAD

**Issue by asomers** [rust-lang/libc#1173]
libc currently uses an instance of Homu as a merge bot.  It's configuration is stored at https://github.com/rust-lang/rust-central-station .  However, Homu has been unmaintained for over two years.  It doesn't understand the GitHub check-suite API, which means it can't work with Cirrus-CI.  Travis is also moving to the check-suite API, and new features might not be reported through the old status API.  So libc should switch to Bors.  Bors is also a hosted service, provided as a GitHub integration, so there's no need for rust-central-station to host it.  I think Bors has all the features that libc needs.

bors docs: https://bors.tech/documentation/getting-started/
original issue: https://github.com/rust-lang/rust-central-station/pull/120

**Comment by gnzlbg** [comment]
See https://internals.rust-lang.org/t/proposal-move-to-bors-ng/5334

**Comment by pietroalbini** [comment]
Note that homu [now supports the GitHub Checks API](https://github.com/rust-ops/homu/pull/10). We're going to test it with Cirrus CI soon.

**Comment by gnzlbg** [comment]
@pietroalbini is there a tracking issue somewhere about moving rust-lang/* from homu to bors? 

I am not sure if it makes sense to move `libc` to bors independently of what rust-lang/rust does.

**Comment by pietroalbini** [comment]
I don't think there is a concrete plan at all.

**Comment by gnzlbg** [comment]
@asomers what are your thoughts on this now that homu has been updated? 

On one hand, I use bors-ng in other projects, and I like it. OTOH, I don't know if it makes strategic sense for libc to switch from homu to bors. Even if that is not the superior technical solution, there is value in using what other rust-lang/rust projects are using (e.g. views of the whole queue, etc.). 

I also think that this is more of an issue that should be tackled by the infra team, than by libc on its own. If homu is not good enough, whether it should be improved, or whether we should migrate to something else, is a decision that I think they should make, not us. I don't think that we can even discuss this issue here appropriately without seeing the whole picture.

**Comment by asomers** [comment]
Now that homu has been updated to understand Github's newer status API there's no urgency.  I still think that bors is superior, but I'm not going to insist upon it.  I'm not even going to press the issue.
