### ISSUE TITLE
f! macro makes functions unnecessarily unsafe and extern

### ISSUE THREAD

**Issue by asomers** [rust-lang/libc#1213]
The `f!` macro is used to reimplement C macros and inline functions in libc.  It eagerly marks these functions as `unsafe` and `extern`.  However, most of them don't actually need to be `unsafe`, and none of them need to be `extern`.  Shall I update the `f!` macro to eliminate the `extern` and make the `unsafe` optional?  This would be a backwards-compatible change, though it might generate "unnecessary unsafe" warnings in consumer code.

Here's an example of an `f!` function that plainly doesn't need to be `unsafe`:
```rust
    pub fn WEXITSTATUS(status: ::c_int) -> ::c_int {
        status >> 8
    }
```

**Comment by alexcrichton** [comment]
I would personally prefer it stays as-is because platforms are often in disagreement about what's a macro, what's an inlined function, and what's an actual symbol. It's not really the place of `libc` to provide nice to use abstractions and/or make design decisions. The point of this crate is to be as simple as possible to append to.

**Comment by asomers** [comment]
Ok.
