### ISSUE TITLE
Platform test question

### ISSUE THREAD

**Issue by jeff-davis** [rust-lang/libc#1219]
I am trying to make my PR pass all of the CI tests.

1. Is there a way I can test more locally so that I don't have to make tons of tiny commits and wait for the CI to run?
1. Are there some strategies to make my changes more likely to be right across many platforms on the first run? Do you just look at all the headers for all of the targets?
1. Are all the tests for this crate passing now, or do some of them fail anyway (I see one that fails because a license question is not accepted... surely that's not from my change)?

**Comment by gnzlbg** [comment]
> Is there a way I can test more locally so that I don't have to make tons of tiny commits and wait for the CI to run?

If you have a Linux system with Docker installed, you can use libc's Docker containers (check how `.travis.yml` calls `run_docker.sh` and you can do this yourself locally).

> Are there some strategies to make my changes more likely to be right across many platforms on the first run? Do you just look at all the headers for all of the targets?

I look at the POSIX / C standard / musl / etc. briefly first, and give it a try and see which archs fail and why. After that I check them out individually, and often you can already feel if the types are "very similar" across all targets, or surprisingly different. If they are different enough, one typically implements them target by target. If afterwards you can consolidate some targets into a top-level module, then go for it.  For the target-by-target implementations, reading their system headers online (e.g. in their git repositories) is what I tend to do, but the version of the target used by libc in CI is often older, so if the tests don't pass, I try to find the right version of the header.

> Are all the tests for this crate passing now, or do some of them fail anyway (I see one that fails because a license question is not accepted... surely that's not from my change)?

Right now all of them pass. The license issue you mention might be caused by something else timing out in the build in CI. Better to ping us in the specific PR so that we can restart the jobs if they hang or fail due to things like these.

**Comment by jeff-davis** [comment]
Thanks! Will do.
