### ISSUE TITLE
Public interface now contains unintended libcore modules

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/libc#1266]
[On master now](https://github.com/rust-lang/libc/blob/577fdc86b239f1909645e60ef6a79f5e7f76b783/src/lib.rs#L48-L93) the root module now reexports via `pub use` a number of modules, but these aren't intended to be part of the public interface of the `libc` crate. I was wondering if this was a mistake perhaps?

**Comment by gnzlbg** [comment]
`Clone`, `Copy` and `Option` shouldn't be pub if private module use is available (looks like a C&P error, but those are hidden). But using `pub use` is required to build in Rust < 1.15.0, where private module use was not available.

**Comment by alexcrichton** [comment]
Ah ok, I think it's probably fine to "expand" the public API on older versions of Rust which are probably no longer in use. Should [these `pub` statements be removed though](https://github.com/rust-lang/libc/blob/577fdc86b239f1909645e60ef6a79f5e7f76b783/src/lib.rs#L61-L69)?

**Comment by gnzlbg** [comment]
> Should [these `pub` statements be removed though](https://github.com/rust-lang/libc/blob/577fdc86b239f1909645e60ef6a79f5e7f76b783/src/lib.rs#L61-L69)?

Yes, see https://github.com/rust-lang/libc/pull/1269

> Ah ok, I think it's probably fine to "expand" the public API on older versions of Rust which are probably no longer in use

I am not sure how libc did it back then, but when trying to compile on Rust 1.13.0, it only compiled for x86_64-unknown-linux-gnu, which was the only target tested, and for that toolchain the build was broken on most other targets due to this issue (private module use).

Exporting those items fixed that, but maybe it should be a hint that we should raise the minimum supported libc version at some point, since the build was broken, and nobody was complaining.

**Comment by alexcrichton** [comment]
Eh well in any case this should be fixed now, thanks!
