### ISSUE TITLE
Allow clippy-driver maybe?

### ISSUE THREAD

**Issue by yaahc** [rust-lang/libc#1544]
## The Dream

So I'm playing around and testing how hard it would be to integrate clippy-driver into `cargo build` and `cargo check` by exporting `RUSTC=clippy-driver`. For most crates this works fine and it builds and outputs just as if it were rustc but also you get clippy warnings.

## The Problem

Turns out libc's build.rs file doesn't like clippy very much, and when you try to build you get the following error.

![Screenshot from 2019-10-10 15-10-29](https://user-images.githubusercontent.com/1993852/66610353-1ef8d800-eb70-11e9-927b-e80f760b2b92.png)

Which seems to be caused by this section of the build.rs file

https://github.com/rust-lang/libc/blob/master/build.rs#L87-L96

## The Proposal

I'm not sure if this is crazy talk but I'd like it if libc could play nicely with clippy-driver. I know old versions will still miscompile so iunno how important helpful fixing this in libc is, but I figured I'd report it anyways

I'm not an expert but I think using `rustc -vV` instead of `rustc --version` might be better and more consistent with how the rest of the ecosystem gets version info from the compiler (thinking about cargo and sccache here). Here is the comparable outputs of those two invocations on rustc and clippy-driver

![Screenshot from 2019-10-10 15-09-50](https://user-images.githubusercontent.com/1993852/66610432-62ebdd00-eb70-11e9-8b9c-5ca9f9a0aa55.png)

**Comment by yaahc** [comment]
One suggestion for fixing this in a backwards compatible(??) way would be to adjust the output of `clippy-driver --version` to output something like

`rustc 1.??.0 + clippy 0.0.??`

Lets just hope to god that nobody is depending directly on the output of `clippy-driver --version`

cc @Manishearth

**Comment by KodrAus** [comment]
Hmm, it looks like `serde` [uses pretty much the same approach](https://github.com/serde-rs/serde/blob/master/serde/build.rs#L114-L117), libraries depending on [`if_rust_version`](https://github.com/ogoffart/if_rust_version/blob/master/build.rs#L8-L11) or [`version_check`](https://github.com/SergioBenitez/version_check/blob/master/src/lib.rs#L88-L90) will possibly report an incorrect version (using `clippy`'s instead of `rustc`'s), and those using [`rustc-version`](https://github.com/Kimundi/rustc-version-rs/blob/master/src/lib.rs#L114-L122) should work.

Making `clippy-driver`'s output support existing version parsers would be pragmatic, but it seems like trying to standardize around `-vV` would be more robust.

**Comment by gnzlbg** [comment]
> I'm not an expert but I think using rustc -vV

Sure, we could try doing that. PRs welcome :)
