### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#1582]
@pietroalbini could we enable github actions for libc ? It has many more buildjobs than Azure, and for libc that's a huge bottleneck.

**Comment by gnzlbg** [comment]
cc @alexcrichton

**Comment by pietroalbini** [comment]
I can't see why not.

**Comment by alexcrichton** [comment]
I'd want to be a little wary of this because [according to their documentation](https://help.github.com/en/github/automating-your-workflow-with-github-actions/about-github-actions#usage-limits) we get 20 concurrent jobs across everything, and while that won't include rust-lang/rust it's not a reason for this or other repositories to go hog wild and add hundreds of builders. I would ideally want to see that the number of builders taken up by libc on github not be that much higher than on azure.

I've personally thought from time to time that the `libc` CI is a bit too ambitious and if it is causing issues with PRs then it should likely be scaled back appropriately.

**Comment by pietroalbini** [comment]
@alexcrichton well, [our plan is actually "GitHub Team"](https://github.com/organizations/rust-lang/settings/billing) (link only for org owners), so we get 60 builders across the `rust-lang` org. If libc limits their concurrency to like 20 parallel builders I don't think that's going to cause issues for othe repos.

**Comment by gnzlbg** [comment]
> I'd want to be a little wary of this because according to their documentation we get 20 concurrent jobs across everything,

Oh, indeed. I thought the limit was 20 jobs per repository, but there are also limits for the whole org. Maybe this is not a good idea and sticking to the rust-lang2 azure org is the best way forward.

>  I would ideally want to see that the number of builders taken up by libc on github not be that much higher than on azure. [...] I've personally thought from time to time that the libc CI is a bit too ambitious and if it is causing issues with PRs then it should likely be scaled back appropriately.

The simplest way to scale it back would be to only run the tests for tier-1 targets here, and just check that tier-2 targets build. That should work fine with the 10 concurrent job limit.

**Comment by alexcrichton** [comment]
Ah if @pietroalbini is right then yes I think we should be fine. I think libc will want to use [`max-parallel`](https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel) though to scale appropriately, and 20 sounds like a good start.

**Comment by gnzlbg** [comment]
> I think libc will want to use max-parallel though to scale appropriately, and 20 sounds like a good start.

I can do that, 20 concurrent jobs should be more than enough (we need around ~15).
