### ISSUE TITLE
use the type that defined in <stdint.h>

### ISSUE THREAD

**Issue by OrigamiKing** [rust-lang/libc#1597]
Why not use the type of <stdint.h>?
I think `pub type c_int32_t = i32;` is better than `pub type c_int = i32;`.

**Comment by qnighy** [comment]
C newly introduced `int32_t` over `int` because `int` may change across platforms. Rust's `i32` and `c_int` are meant to reflect the difference.

Therefore `i32` (`int32_t`) is usually better than `c_int` (`int`), but in `libc` this isn't the case. Correspondence to the existing interface (as written in C headers) is more important than fixing sizes between platforms. I guess that's why `c_int` exists in the first place.

We can use `i32` if the corresponding C header says `int32_t`, and `c_int` if `int`. In any case, `c_int32_t` seems redundant to me, unlike `c_int`.

**Comment by gnzlbg** [comment]
Notice that we do expose `pub type int32_t = i32;` aliases, but these are deprecated since there is no need to actually use them (you can just use `i32`). If you prefer to use the aliases you can do so, e.g., by allowing the deprecation warnings, but we might remove these aliases in a future libc version, so I recommend to just use `i32` directly instead.
