### ISSUE TITLE
const-extern-fn feature still requires nightly, but appears to be available >= 1.40

### ISSUE THREAD

**Issue by bluejekyll** [rust-lang/libc#1901]
In build.rs the check `if !is_nightly || rustc_minor_ver < 40` will always fail if not using a nightly compiler. It appears this should be able to be enabled on stable at this point. Is this a bug in the conditional logic?

**Comment by JohnTitor** [comment]
`const_extern_fn` isn't stabilized and it's added in 1.40. This condition will trigger a panic if rustc isn't nightly (because it's unstable) or is less than 1.40 (because the compiler doesn't know that feature). Note that nightly compilers also have minor versions, e.g. 1.40.0-nightly. So it is correct for me.
cc @Aaron1011

**Comment by JohnTitor** [comment]
I'm going to close this assuming my understanding is correct. Feel free to correct me and re-open this issue :)
