### ISSUE TITLE
Type insistent of libc::RLIMIT_NOFILE etc

### ISSUE THREAD

**Issue by mitnk** [rust-lang/libc#2029]
On Mac it's `i32` and on Linux it's `u32`? libc version 0.2.82.

**Comment by mitnk** [comment]
In code some are defined as `c_int`, some are `__rlimit_resource_t`:
```
...
src/unix/linux_like/emscripten/mod.rs
1520:pub const RLIMIT_NOFILE: ::c_int = 7;

src/unix/linux_like/linux/gnu/b32/arm/mod.rs
197:pub const RLIMIT_NOFILE: ::__rlimit_resource_t = 7;
...
```
while __rlimit_resource_t is defined as `c_uint`.

**Comment by maxbla** [comment]
I believe [this is intentional](https://github.com/rust-lang/libc/issues/1767#issuecomment-632070405) and due to upstream weirdness - on macOS, [getrlimit takes an int](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getrlimit.2.html) as expected. But in glibc, the situation is complicated. The glibc authors tried to be clever and use an enum like this
```C
/* from /usr/include/sys/resource.h */

/* The X/Open standard defines that all the functions below must use
   `int' as the type for the first argument.  When we are compiling with
   GNU extensions we change this slightly to provide better error
   checking.  */
#if defined __USE_GNU && !defined __cplusplus
typedef enum __rlimit_resource __rlimit_resource_t;
typedef enum __rusage_who __rusage_who_t;
typedef enum __priority_which __priority_which_t;
#else
typedef int __rlimit_resource_t;
typedef int __rusage_who_t;
typedef int __priority_which_t;
```
Using the enum typedef, the integral type of the value is [technically not specified](https://stackoverflow.com/questions/159034/are-c-enums-signed-or-unsigned) - it could be signed or unsigned. Using gcc, it happens to be unsigned. There's also the problem that I don't know if libc assumes gnu extensions are enabled (the __USE_GNU macro).
