### ISSUE TITLE
Drop support for Rumprun

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/libc#2091]
rustc dropped the support for Rumprun in https://github.com/rust-lang/rust/pull/82594. We could drop the support on libc as we did for CloudABI.
cc #2090

**Comment by joshtriplett** [comment]
:+1: to removing this support, since Rust did.

We may want to establish a policy here. Under what circumstances can we remove support for a target? Can we always do so when Rust does, or do we have any special considerations to take into account if the target was previously tier 1/2 and available in stable? Can we count on projects to have older versions of libc in their lockfiles if they need to run on older targets?

I think the answer is that we can remove targets when Rust does, but this seems worth confirming and documenting.

**Comment by JohnTitor** [comment]
Note: I'm holding this off due to circumstances.

Agree, I also think we can drop support for Tier 3 once rustc does. And for tier 1/2, I'm not 100% sure but does rustc suddenly drop their support without downgrading generally? If rustc does it, I would think there was a reasonable reason (and we should consider if libc also should drop the support, it will highly depend on the situation, I imagine). I'm happy to document this as a "target support policy" or something else if needed.
@rust-lang/libc Feel free to comment here if you have different opinions.

**Comment by workingjubilee** [comment]
> Agree, I also think we can drop support for Tier 3 once rustc does. And for tier 1/2, I'm not 100% sure but does rustc suddenly drop their support without downgrading generally?

Historically, Rust targets have dropped from as high as tier 1 to tier 3 as a single change, e.g. https://github.com/rust-lang/rfcs/pull/2837/files but have not been abruptly removed from tier 1 or tier 2.
