### ISSUE TITLE
locale, monetary, time stuff

### ISSUE THREAD

**Issue by mrhota** [rust-lang/libc#242]
Would this be the appropriate project for system locale.h, monetary.h, and time.h defs and bindings?

**Comment by alexcrichton** [comment]
I believe so! The scope of this library is defined by [RFC 1291](https://github.com/rust-lang/rfcs/blob/master/text/1291-promote-libc.md) and so long as these headers fall in that category it should be good to go.

**Comment by mrhota** [comment]
Heck yes! Thanks for the link.

For reference, the above bindings would be relevant for (at least) [rust-locale/rust-locale](https://github.com/rust-locale/rust-locale) and [rust-datetime/datetime](https://github.com/rust-datetime/datetime)

**Comment by alexcrichton** [comment]
Ah yeah those look quite appropriate to add to libc!

I also meant to close earlier, so I'll do so now. Feel free to send a PR any time :)

**Comment by jan-hudec** [comment]
The [`locale` crate (rust-locale/rust-locale)](https://github.com/rust-locale/rust-locale) already has bindings for _GNU_ LibC `locale_t` and `nl_langinfo_l` functions. It needs to be cleaned up to work on OSX and Musl, which also have the functions, but different set of langinfo items.

The functions do fit the scope, since they live in `libc.so` itself. However, it is just a couple of functions, so I am fine with having them declared privately in [`locale` (rust-locale/rust-locale)](https://github.com/rust-locale/rust-locale)).

`datetime` should _not_ need the same functions; it will need to cooperate (without presuming which way the dependency will be; it can be either way) with `locale` for the formatting support anyway.
