### ISSUE TITLE
Unnecessary `mut`in the epoll_ctl API

### ISSUE THREAD

**Issue by mohamed-said** [rust-lang/libc#3057]
In the `epoll_ctl` API, I's required that the last parameter `struct epoll_event *event` as `*mut`.

I have checked the linux implementation for `epoll_ctl` and this parameter's value is never assigned to, 
for example: `event = foo;`

Is there a reason why it's required to pass this parameter as `*mut` and not `*const` ?

**Comment by Dann239** [comment]
I also had the same question a while ago. Apparently, there is!

Relevant link: https://stackoverflow.com/questions/38536043/may-epoll-ctl-modify-the-epoll-event-structure-passed-to-it

TLDR: it is indeed intentional and shouldn't be made const because "doing that would prevent
other non-const operations to be added later on"

Hope this helps

**Comment by JohnTitor** [comment]
The libc crate just mirrors upstream declarations and it helps us review/maintain items (we test items by checking comparing with ABIs/declarations on C).
And it has some meaning on upstream, so it shouldn't make sense to make a change here.
Closing as wontfix, thanks for reporting anyway!

**Comment by mohamed-said** [comment]
I understand. Thank you very much for the explanation @Dann239 & @JohnTitor. And sorry for the late reply. :)
