### ISSUE TITLE
Hash-Pin Dependencies

### ISSUE THREAD

**Issue by joycebrum** [rust-lang/libc#3221]
Hi I'm Joyce from Google and I'm working on helping many open source projects on improving their supply chain security posture.

## Description

I would like to suggest a security practice recommended by the [OpenSSF Scorecard][scorecard-repo] which is to hash pin dependencies to prevent dependency-confusion and typosquatting attacks. 

The change would only be applied to GitHub workflows, dockerfiles and shell scripts dependencies.

This means:
- Hash pinning GitHub Workflow actions.
- Hash pinning the image of the OS/runner on dockerfiles.
- Using --requirechecksums on choco installs.

I can submit one PR for each type of change above to be easier to review if you prefer. Just let me know if that's the case.

Along with hash-pinning dependencies, I also recommend adopting dependabot or renovatebot to help keep the dependencies up to date. Both tools can update  hashes and associated semantic version comments. 

Let me know if you are open to evaluate those changes and I'll submit the PRs ASAP. 

Any questions or concerns just let me know.
Thanks!

## Additional Context

For more informations about dependency confusion / typosquatting attacks:
- [Detection of malicious packages][google-blog]
- [Counter dependency confusion (aka substitution) attacks][azure-paper] 

For more informations about the dependency-update tools:
- [Dependabot][dependabot]
- [Renovatebot][renovatebot]

[scorecard-repo]: https://github.com/ossf/scorecard
[google-blog]: https://security.googleblog.com/2022/04/
[azure-paper]: https://azure.microsoft.com/en-us/resources/3-ways-to-mitigate-risk-using-private-package-feeds/
[dependabot]: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
[renovatebot]:https://www.mend.io/renovate/

**Comment by workingjubilee** [comment]
@joycebrum

1. This crate has 0 dependencies due to its particular role in the Rust ecosystem.
2. Its test crate has only a few minimal dependencies, all of which are either directly controlled by the Rust Project, or are directly controlled by a trusted member of the Rust Project.
3. Pinning, as you describe, is counter to recommended practice in the Rust ecosystem due to peculiarities of Cargo's resolver.

But thank you for the offer to help.

**Comment by workingjubilee** [comment]
...and we control most of the GitHub Actions too.

For the ones we don't... we have much bigger things to worry about if `actions/checkout@v3` is suborned, and the amount of maintainer time/energy to evaluate automated warnings from things like dependabot and renovatebot is *extremely* thin, so increasing the already-high maintenance burden of this crate, merely to obtain some points on a scorecard from the OSSF, would be... counterproductive. Because this crate changes incredibly slowly, including its CI, I am not seriously concerned.

If you have a more... holistic security recommendation that accounted for this being a crate being controlled by a gaggle of programmers who are often accused of being anxiety-ridden paranoiacs already, we would probably be interested.

**Comment by joycebrum** [comment]
Hi @workingjubilee thanks for the return!

No problems, there are really strong cons on hash pinning and there is no right answer on this matter. Besides, the workflows being with permissions minimally scoped as it is, it is safe enough! 🙏🏼
