### ISSUE TITLE
Implement Default for termios

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/libc#573]
I don't know if this is useful for most structs, but at least for `termios`, it would be nice if there was a default implementation. Maybe another struct macro can exist that derives `Default` as well and that can be used for this kind of situation and it can be used on a per-struct basis.

**Comment by Susurrus** [comment]
I'd be happy to file a PR for this, but I first wanted some feedback on whether such a change would even be considered.

**Comment by alexcrichton** [comment]
Currently the API of the libc crate is fairly rigorously defined in [RFC 1291](https://github.com/rust-lang/rfcs/blob/master/text/1291-promote-libc.md), and currently `Default` is not included in exported APIs. In that sense I would personally prefer to see an RFC for a change such as this rather than a PR.

**Comment by Susurrus** [comment]
Would I therefore create an RFC that would amend RFC1291?

**Comment by alexcrichton** [comment]
I think an amendment to RFC 1291 is fine, but it should still clearly state motivation, implementation, etc.

**Comment by alexcrichton** [comment]
I'm going to close this in favor of a future RFC for now

**Comment by pickfire** [comment]
Is this valid now?
