### ISSUE TITLE
Verify libc builds with --cfg stdbuild

### ISSUE THREAD

**Issue by nagisa** [rust-lang/libc#68]
Android CI only check whether tests can be run and pass, but do not check whether library actually builds under Android.

This is important to test, because e.g. `librt` does not exist in Android devkit (and liblibc does not actually use it either) and we still try to link to it since #66.

**Comment by alexcrichton** [comment]
I don't understand what's at play here, if we're ensuring tests run and pass (which requires the library to build) then I don't see what the "flaw" is.

This library doesn't actually link anything unless passed `--cfg stdbuild`, which may be what you're referring to, but it's not clear to me.

**Comment by nagisa** [comment]
The test binary itself is built outside of the simulator, which means that we do not check whether test binary actually builds under android. Only that it runs and all tests pass.

**Comment by alexcrichton** [comment]
To the best of my knowledge there's no compiler in the simulator itself, the only option for compiling is outside. Even if there were, however, there's no Rust compiler that runs in the simulator and there's no reason cross compiling should be a problem. 

Can you elaborate a bit more on why you opened this? Was it to detect how `-lrt` is missing on Android?

**Comment by nagisa** [comment]
> Can you elaborate a bit more on why you opened this? Was it to detect how -lrt is missing on Android? 

Exactly :)

**Comment by alexcrichton** [comment]
Ok, in that case I've updated the title to reflect what's going on. There's no CI that this library builds with `--cfg stdbuild`, and there's also no verification that it links with that. Android is *thoroughly* tested right now, so that's not the problem, it's moreso that nothing tests the linkage of this library because that's what the standard library is responsible for.

One half of this will be building with `--cfg stdbuild` (on nightly only), and the second half will be figuring out how to link that rlib into a binary to test the linkage. I don't know how to do the second half.

**Comment by alexcrichton** [comment]
This is now basically done by https://github.com/rust-lang/libc/pull/146 as we build with `no_std`
