### ISSUE TITLE
freopen() appears to be unusable (No stdin/stdout/stderr consts)

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/libc#7]
freopen() is the POSIX libc function for redirecting stdin, stdout & stderr. The libc function takes a value of libc::FILE for the file field. libc::FILE is an empty enum, and there are no consts for stdin/stdout/stderr as there are in C. I cannot figure out how to call freopen() correctly.

Is this a genuine bug or am I missing the correct way to do this?

**Comment by alexcrichton** [comment]
Yeah currently these constants are not bound, but it should be fine to add them at any time basically! Otherwise though I'd recommend just making a C shim which returns the values so you can use them. We generally don't keep track of issues like this though, so I'm going to close it, but feel free to make a PR against rust-lang/rust at any time!
