### ISSUE TITLE
Make the ci infrastructure reusable from other crates

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#834]
I'd like to reuse most / all of the ci infrastructure from the `stdsimd` crate, so I'd like to ask if it would be possible to refactor this in such a way that this becomes possible.

**Comment by malbarbo** [comment]
@gnzlbg I believe that [cross](https://github.com/japaric/cross) and [trust](https://github.com/japaric/trust) already provides reusable ci infrastructure. I known you are interested in running the foreign binaries in qemy-system because of https://github.com/japaric/cross/issues/146.

I'm [trying](https://github.com/japaric/cross/pull/153) to add a qemu-system runner in cross, so I suppose we can discuss this issue there.

**Comment by gnzlbg** [comment]
@malbarbo awesome, I'll subscribe there :)
